#!/system/bin/sh
# simplify uninstall of busybox and links
# written by DRockstar for SDX Developers
# assumes alternate busybox installation in path

PATH=/sbin:/bin:/system/bin:/system/xbin:/data/local/tmp
busybox mount -o remount,rw /system
for wdir in /system/bin /system/xbin; do
  find $wdir -type l | while read line; do
    btest=`busybox readlink $line`
    if busybox test "`echo $btest | busybox grep busybox`" != "" -o "`echo $btest | busybox grep recovery`" != ""; then
      rm $line
      if busybox test -e $btest -a "$btest" != "/sbin/busybox"; then
        rm $btest
      fi
    fi
  done
done
busybox mount -o remount,ro /system

