#!/sbin/sh
# Epic Root Uninstaller by DRockstar
# Modified for Clean Kernel script
# assumes alternate busybox install in path

PATH=/sbin:/bin:/system/bin:/system/xbin:/data/local/tmp

# busybox command variables
BUSYBOX="/sbin/busybox"

AWK="$BUSYBOX awk"
CHMOD="$BUSYBOX chmod"
CHOWN="$BUSYBOX chown"
CP="$BUSYBOX cp"
DF="$BUSYBOX df"
ECHO="$BUSYBOX echo"
FIND="$BUSYBOX find"
GREP="$BUSYBOX grep"
LN="$BUSYBOX ln"
MOUNT="$BUSYBOX mount"
READLINK="$BUSYBOX readlink"
RM="$BUSYBOX rm"
SLEEP="$BUSYBOX sleep"
TEST="$BUSYBOX test"

$MOUNT -o remount,rw /
$MOUNT -o remount,rw /system

for wdir in /system/bin /system/xbin; do
  $FIND $wdir -type l | while read line; do
    btest=`$READLINK $line`
    if $TEST "`$ECHO $btest | $GREP busybox`" != "" -o "`$ECHO $btest | $GREP recovery`" != ""; then
      $RM $line
      if $TEST -e $btest -a "$btest" != "/sbin/busybox"; then
        $RM $btest
      fi
    fi
  done
done

# List of all known files used for root
cleanlist="
/data/app/Superuser.apk
/data/dalvik-cache/system@app@Superuser.apk@classes.dex
/data/local/root.sh
/data/local/tmp/root.sh
/data/local/tmp/rageagainstthecage-arm5.bin
/etc/group
/etc/passwd
/etc/resolv.conf
/system/app/Superuser.apk
/system/bin/busybox
/system/bin/jk-su
/system/bin/joeykrim-root.sh
/system/bin/playlogo-orig
/system/bin/remount
/system/bin/resolv.conf
/system/bin/su
/system/etc/group
/system/etc/passwd
/system/etc/resolv.conf
/system/xbin/busybox
/system/xbin/remount
/system/xbin/su
/system/xbin/keytimer
/data/local/timer_delay
/system/bin/recoveryres
/system/bin/recoveryfiles
"

# Remove all root files, as listed in cleanlist variable
for line in $cleanlist; do
  $RM -rf $line
done

$SLEEP 3

$MOUNT -o remount,ro /
$MOUNT -o remount,ro /system
